# ------------------------------------------------------------------------------
#  File:         phb-pro.yaml
#  File Type:    ESPHome YAML Main
#  Purpose:      PumpHouseBoss Pro Variant Main
#  Version:      0.8.0d
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  PumpHouseBoss Pro Variant is a Water Distribution System
#                Monitor and controller built on the ESP32s3 platform.
#
#  Features:     - Ingress and egress flow monitoring, metering
#                - Over/under flow-rate detection, alerts and alarms
#                - Automated solenoid control for emergency water-shutoff or
#                  water-flow management/control
#                - Manual emergency override to shut-off water-flow
#                - 4 line LCD (lcd_pcf8574 interface)
#                - Historical flow-rate/usage graphing
#                - Home Assistant integration via ESPHome
#                - Supports up to 8 MMUs
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         Build-time Variable Substitution:
#                - Variables in the form __VAR_NAME__ are automatically replaced
#                  with project-specific values during the build process
#                  (see Makefile and sed logic).
#                - This enables flexible, reusable configuration for multiple
#                  hardware variants.
#                - Do not edit these variables directly in the build output.
#                  (Example: __NODE_NAME__, __PLATFORM__, __VERSION__)
#
#  Note:         Co-developed with GitHub Copilot by OpenAI.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
#  YAML linter configuration
#   - Disables quoted-strings rule for improved readability
# ------------------------------------------------------------------------------
# yamllint disable rule:quoted-strings


# ------------------------------------------------------------------------------
#  Node identity, version, and hardware pin assignments
#   - Provides substitutions for node name, friendly name, version, and key pins
#   - Used throughout the configuration for maintainability
#   - Parameters:
#       node_name: Node ID used in ESPHome and logs
#       friendly_name: Human-readable name for dashboards
#       version: Firmware version tag injected into logs and sensors
#       flow_sensor_pin: Primary flow sensor pulse counter input
#       test_output_pin: GPIO test and verification pin
#       watchdog_timeout: Hardware watchdog timeout period
#       watchdog_trigger_pin: External watchdog trigger output
#       watchdog_early_trigger: Early trigger before timeout
# ------------------------------------------------------------------------------
substitutions:
  chip_set: "__PLATFORM__"
  node_name: "__NODE_NAME__"
  friendly_name: "__FRIENDLY_NAME__"
  version: "__VERSION__"
  watchdog_timeout: "30s"
  watchdog_trigger_pin: "GPIO07"
  watchdog_early_trigger: "25s"
  led_power_pin: "GPIO7"
  led_wifi_status_pin: "GPIO15"
  led_host_status_pin: "GPIO16"
  led_mmu_status_pin: "GPIO17"
  mmu_sensor_0_pin: "GPIO19"


# ------------------------------------------------------------------------------
#  Common package includes for modular configuration
#   - Modularizes board, display, network, OTA, logging, and watchdog config
#       display: Display configuration (e.g., ST7789V panel)
#       wifi: Wi-Fi credentials, static IP, and fallback
#       ota: OTA settings (port, auth)
#       web: Web interface (http://<device>.local)
#       logging: USB/UART logging config (level, baud)
#       watchdog: System reliability watchdog component
# ------------------------------------------------------------------------------
packages:
  esp32s3:     !include common/__PLATFORM__.yaml
  wifi:        !include common/wifi.yaml
  ota:         !include common/ota.yaml
  api:         !include common/api.yaml
  web:         !include common/web_server.yaml
  logging:     !include common/logging.yaml
  watchdog:    !include common/watchdog.yaml
  indications: !include common/indications.yaml
  display:     !include common/display_pcf8574.yaml
  mmu:         !include common/mmu.yaml


# ------------------------------------------------------------------------------
#  Global Variables
#   - Defines internal variables for use in automations and logic blocks
#   - Example: ha_connected tracks Home Assistant API connection status
#   - Parameters:
#       id: Variable name (referenced in lambdas)
#       type: Data type (e.g., bool, int, float)
#       restore_value: Whether to restore value after reboot (no for runtime state)
#       initial_value: Value at boot
# ------------------------------------------------------------------------------
globals:
  - id: ha_connected
    type: bool
    restore_value: no
    initial_value: 'false'


# ------------------------------------------------------------------------------
#  ESPHome-specific metadata and on_boot logic
#   - Sets node name and friendly name
#   - Publishes firmware version to Home Assistant on boot
#   - Parameters:
#       name: Node name
#       friendly_name: Human-readable name
#       on_boot: Actions to perform on boot
#   - NOTE: ESPHome does not currently support reset diagnostics on ESP32-S3.
#           These are placeholders until native support is available.
# ------------------------------------------------------------------------------
esphome:
  name: __NODE_NAME__
  friendly_name: __FRIENDLY_NAME__
  on_boot:
    priority: -100
    then:
      - text_sensor.template.publish:
          id: firmware_version
          state: "__VERSION__"
      - text_sensor.template.publish:
          id: reset_reason
          state: "Power On Reset"
      - sensor.template.publish:
          id: last_reset_code
          state: 1


# ------------------------------------------------------------------------------
#  I2C Bus Configuration
#   - Configures the I2C bus for peripherals (e.g., LCD, sensors)
#   - sda: GPIO pin used for I2C data (SDA)
#   - scl: GPIO pin used for I2C clock (SCL)
#   - scan: true enables automatic device address scanning (shows in logs)
# ------------------------------------------------------------------------------
i2c:
  sda: 18
  scl: 9
  scan: true


# ------------------------------------------------------------------------------
#  ESP32 Reset Diagnostics (Fallback for ESP32-S3)
#   - ESPHome does not yet support esp32_reset_reason/last_reset on ESP32-S3.
#   - These template sensors default to 'Power On Reset' (string) and 1 (numeric).
#   - Update to native sensors when ESPHome adds support for ESP32-S3.
#   - Parameters:
#       platform: template
#       name: Sensor name (shown in Home Assistant)
#       id: Sensor ID for internal reference
#   - NOTE: ESPHome does not currently support reset diagnostics on ESP32-S3.
#           These are placeholders until native support is available.
# ------------------------------------------------------------------------------
sensor:
  - platform: template
    name: "Last Reset Code"      # Fallback: always 1 (Power On Reset code)
    id: last_reset_code
    lambda: |-
      return 1;
    update_interval: never
  - platform: uptime
    name: "Uptime"                # Uptime in seconds since boot
    id: uptime_sensor


# ------------------------------------------------------------------------------
#  Uptime and flow rate sensors (hall-effect pulse counter)
#   - Uptime sensor: seconds since boot
#   - Flow rate sensor: hall-effect pulse counter, configurable input pin
#   - Calibration factor converts pulses to L/min
#   - Parameters:
#       platform: Sensor platform (uptime, pulse_counter)
#       pin: Input pin for pulse counter
#       name: Sensor name
#       id: Sensor ID
#       update_interval: Update frequency
#       count_mode: Pulse counting mode
#       internal_filter: Filter for pulse input
#       unit_of_measurement: Measurement units
#       accuracy_decimals: Number of decimals
#       filters: Calibration factor
# ------------------------------------------------------------------------------
binary_sensor:
  - platform: status
    id: wifi_connected
  - platform: template
    id: system_boot
    name: "System Boot"
    lambda: |-
      // Always true after boot
      return true;


# ------------------------------------------------------------------------------
#  Template text sensors
#   - Firmware Version: Publishes the firmware version string to Home Assistant
#   - Reset Reason: Fallback for ESP32-S3, always 'Power On Reset'
#   - Parameters:
#       platform: template
#       name: Sensor name
#       id: Sensor ID
#       icon: Home Assistant icon (optional)
#       update_interval: Update frequency
#       lambda: Lambda function for value
#
# NOTE: ESPHome does not currently support reset diagnostics on ESP32-S3.
# This is a placeholder until native support is available.
# ------------------------------------------------------------------------------
text_sensor:
  - platform: template
    name: "Firmware Version"      # User-visible sensor name in HA
    id: firmware_version
    icon: "mdi:tag"
    update_interval: never        # Static value set only on boot
    lambda: |-
      return {"__VERSION__"};
  - platform: template
    name: "Reset Reason"          # Fallback: always 'Power On Reset' on ESP32-S3
    id: reset_reason
    update_interval: never
    lambda: |-
      return {"Power On Reset"};
