# ==============================================================================
#  File:         phb-pro.mk
#  File Type:    Makefile
#  Purpose:      PumpHouseBoss Pro Variant build variables and defaults
#  Version:      0.9.0d
#  Date:         2025-07-26
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This variant-specific configuration file describes default
#                values used to build the PumpHouseBoss Pro implementation.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ==============================================================================

# Required configuration values
VARIANT        ?= phb-pro
PLATFORM       ?= esp32s3
DEVICE_NAME    ?= phb-pro
NODE_NAME      ?= phb-pro-node
FRIENDLY_NAME  ?= PumpHouseBoss Pro
