#!/bin/bash
#
# ------------------------------------------------------------------------------
#  @file        configure.sh
#  @brief       Interactively generate a .makefile for the project
#
#  @author      Roland Tembo Hendel
#  @email       rhendel@nexuslogic.com
#  @license     GNU General Public License v3.0
#               SPDX-License-Identifier: GPL-3.0-or-later
#
#  @copyright   Copyright (c) 2025 Roland Tembo Hendel
#               This program is free software: you can redistribute it and/or
#               modify it under the terms of the GNU General Public License
#               as published by the Free Software Foundation, either version 3
#               of the License, or (at your option) any later version.
#
#               This program is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public License
#               along with this program. If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

echo "=== ESPHome Device Setup ==="
echo

if [[ -f .makefile ]]; then
  read -rp ".makefile already exists. Overwrite? [y/N]: " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || exit 1
fi

read -rp "Enter device name (e.g., sysmon-ph): " NODE_NAME
read -rp "Enter friendly name (e.g., sysmon-ph): " FRIENDLY_NAME
read -rp "Enter static IP address: " NODE_STATIC_IP
read -rp "Enter gateway address: " NODE_GATEWAY
read -rp "Enter subnet mask [255.255.255.0]: " NODE_SUBNET
NODE_SUBNET=${NODE_SUBNET:-255.255.255.0}
read -rp "Enter primary DNS server [8.8.8.8]: " NODE_DNS1
NODE_DNS1=${NODE_DNS1:-8.8.8.8}
read -rp "Enter secondary DNS server [1.1.1.1]: " NODE_DNS2
NODE_DNS2=${NODE_DNS2:-1.1.1.1}
read -rp "Enter COM port (e.g., COM6): " COM_P:ORT
read -rp "Enter full path to esphome (or leave blank to use 'esphome' in PATH): " ESPHOME

echo
echo "Writing .makefile..."

cat > .makefile <<EOF
# Auto-generated by configure.sh

NODE_NAME      = $NODE_NAME
FRIENDLY_NAME  = $FRIENDLY_NAME
NODE_STATIC_IP = $NODE_STATIC_IP
NODE_GATEWAY   = $NODE_GATEWAY
NODE_SUBNET    = $NODE_SUBNET
NODE_DNS1      = $NODE_DNS1
NODE_DNS2      = $NODE_DNS2
COM_PORT       = $COM_PORT
EOF

if [[ -n "$ESPHOME" ]]; then
  echo "ESPHOME        = $ESPHOME" >> .makefile
fi

echo ".makefile created successfully!"

