# ------------------------------------------------------------------------------
#  @file        main.yaml
#  @brief       Pumphouie System Monitor built on the ESP32S3 platform.
#  @details     Functions include:
#                 - ingress flow-monitoring
#                 - egress flow-monitoring
#                 - alarms and alerts
#                 - modular YAML includes for board, display, network, OTA, logging, watchdog
#                 - Home Assistant integration via ESPHome
#
#  @author      Roland Tembo Hendel
#               <mailto:rhendel@nexuslogic.com>
#
#  @license     GNU General Public License v3.0
#               SPDX-License-Identifier: GPL-3.0-or-later
#  @copyright   Copyright (c) 2025 Roland Tembo Hendel
#               This program is free software: you can redistribute it and/or
#               modify it under the terms of the GNU General Public License
#               as published by the Free Software Foundation, either version 3
#               of the License, or (at your option) any later version.
#
#               This program is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public License
#               along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#  @note        Co-developed with GitHub Copilot by OpenAI.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# @brief YAML linter configuration
# @details
#   - Disables quoted-strings rule for improved readability
# ------------------------------------------------------------------------------
# yamllint disable rule:quoted-strings


# ------------------------------------------------------------------------------
# @brief Substitutions for node identity, version, and hardware pin assignments
# @details
#   - node_name: Node ID used in ESPHome and logs
#   - friendly_name: Human-readable name for dashboards
#   - version: Firmware version tag injected into logs and sensors
#   - flow_sensor_pin: Primary flow sensor pulse counter input
#   - test_output_pin: GPIO test and verification pin
#   - watchdog_timeout: Hardware watchdog timeout period
#   - watchdog_trigger_pin: External watchdog trigger output
#   - watchdog_early_trigger: Early trigger before timeout
# @param node_name Node ID used in ESPHome and logs
# @param friendly_name Human-readable name for dashboards
# @param version Firmware version tag injected into logs and sensors
# @param flow_sensor_pin Primary flow sensor pulse counter input
# @param test_output_pin GPIO test and verification pin
# @param watchdog_timeout Hardware watchdog timeout period
# @param watchdog_trigger_pin External watchdog trigger output
# @param watchdog_early_trigger Early trigger before timeout
# ------------------------------------------------------------------------------
substitutions:
  node_name: __NODE_NAME__
  friendly_name: __FRIENDLY_NAME__
  version: __VERSION__
  flow_sensor_pin: "GPIO04"
  test_output_pin: "GPIO05"
  watchdog_timeout: "30s"
  watchdog_trigger_pin: "GPIO07"
  watchdog_early_trigger: "25s"

# ------------------------------------------------------------------------------
# @brief Common package includes for modular configuration
# @details
#   - esp32: ESP32 board and framework config
#   - display: Display configuration (e.g., ST7789V panel)
#   - wifi: Wi-Fi credentials, static IP, and fallback
#   - ota: OTA settings (port, auth)
#   - web: Web interface (http://<device>.local)
#   - logging: USB/UART logging config (level, baud)
#   - watchdog: System reliability watchdog component
# ------------------------------------------------------------------------------
packages:
  esp32:    !include ../common/esp32s3.yaml
  display:  !include ../common/display_st7789.yaml
  wifi:     !include ../common/wifi.yaml
  ota:      !include ../common/ota.yaml
  web:      !include ../common/web_server.yaml
  logging:  !include ../common/logging.yaml
  watchdog: !include ../common/watchdog.yaml

# ------------------------------------------------------------------------------
# @brief ESPHome-specific metadata and on_boot logic
# @details
#   - Sets node name and friendly name
#   - Publishes firmware version to Home Assistant on boot
# ------------------------------------------------------------------------------
esphome:
  name: __NODE_NAME__
  friendly_name: __FRIENDLY_NAME__
  on_boot:
    priority: -100
    then:
      - text_sensor.template.publish:
          id: firmware_version
          state: 0.6.1           # Publishes version string to Home Assistant on boot

# ------------------------------------------------------------------------------
# @brief Template sensor exposing firmware version as Home Assistant text_sensor
# @details
#   - Publishes the firmware version string to Home Assistant
# ------------------------------------------------------------------------------
text_sensor:
  - platform: template
    name: "Firmware Version"      # User-visible sensor name in HA
    id: firmware_version
    icon: "mdi:tag"
    update_interval: never        # Static value set only on boot
    lambda: |-
      return {"__VERSION__"};

# ------------------------------------------------------------------------------
# @brief Uptime and flow rate sensors (hall-effect pulse counter)
# @details
#   - Uptime sensor: seconds since boot
#   - Flow rate sensor: hall-effect pulse counter, configurable input pin
#   - Calibration factor converts pulses to L/min
# ------------------------------------------------------------------------------
sensor:
  - platform: uptime
    name: "Uptime"                # Uptime in seconds since boot
    id: uptime_sensor

  - platform: pulse_counter
    pin: 
      number: ${flow_sensor_pin}   # Configurable flow sensor input pin
      mode:
        input: true
        pullup: true              # Standard pull-up configuration
    name: "Flow Rate"
    id: flow_rate_sensor
    update_interval: 1s           # Fast update to catch transitions
    count_mode:
      rising_edge: INCREMENT      # Count rising edges
      falling_edge: DISABLE       # Ignore falling edges
    internal_filter: 1us          # Very fast filter to catch high-frequency signals
    unit_of_measurement: "gpm"
    accuracy_decimals: 2
    filters:
      - multiply: 0.1             # Calibration factor (pulses to L/min)

# ------------------------------------------------------------------------------
# @brief GPIO test output to verify pin mapping
# ------------------------------------------------------------------------------
output:
  - platform: gpio
    pin: ${test_output_pin}       # Configurable test output pin
    id: test_output

# ------------------------------------------------------------------------------
# @brief Test switch to toggle GPIO for pin verification
# ------------------------------------------------------------------------------
switch:
  - platform: output
    name: "GPIO Test Toggle"
    output: test_output
    id: gpio_test_switch

