# ------------------------------------------------------------------------------
#  File:         default.mk
#  File Type:    Makefile Include
#  Purpose:      PumpHouse Boss Build Default Configuration
#  Version:      0.8.0d
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This configuration file describes the default set of variables
#                and defaults used by the Master Makefile.
#                Users may include a <custom>.mk configuration file based on this
#                template to override the default values specified in this file.
#                The Master Makefile will automatically include overrides
#                specified in the config.mk file of the project root if it exists.
#                Alternatively, users may pass the name of a custom configuration
#                file to the Master Makefile by specifying an argument to make.
#                i.e. make CONFIG=<custom.mk>
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# Required configuration values
VARIANT        ?= phb-std
DEVICE_NAME    ?= phb-std-default
NODE_NAME      ?= phb-std-default
FRIENDLY_NAME  ?= PumpHouseBoss Standard Default
