# ------------------------------------------------------------------------------
#  File:         phb-std-test.mk
#  File Type:    Makefile Include
#  Purpose:      Default build configuration for PumpHouse Boss Standard test instance
#  Version:      0.7.1
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This configuration file describes variables and defaults used
#                to build the PumpHouse Boss Std test instance.
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# Required configuration values
VARIANT        ?= phb-std
DEVICE_NAME    ?= phb-std-test
NODE_NAME      ?= phb-std-test-00
FRIENDLY_NAME  ?= PumpHouseBoss Standard Test Node
