# ------------------------------------------------------------------------------
#  File:         phb-pro-max-test.mk
#  File Type:    Makefile Include
#  Purpose:      Default build configuration for PumpHouse Boss Pro Max test instance
#  Version:      0.7.0
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This configuration file describes variables and defaults used
#                to build the PumpHouse Boss Pro Max test instance.
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# Required configuration values
VARIANT        ?= phb-pro-max
DEVICE_NAME    ?= phb-pro-max-test
NODE_NAME      ?= phb-pro-max-test-00
FRIENDLY_NAME  ?= PumpHouseBoss Pro Max Test Node
