# ------------------------------------------------------------------------------
#  File:         template.mk
#  File Type:    Makefile Include
#  Purpose:      PumpHouse Boss Build Configuration Template
#  Version:      0.8.0d
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This template describes variables and defaults used to build all
#                PumpHouse Boss variants. Users may copy this template to a
#                separate <custom>.mk file for editing, to override the default
#                values passed to the Master Makefile.
#                Users may include a separate <custom>.mk configuration file based
#                on this template to override the default values specified in this
#                file.
#                The Master Makefile will automatically include overrides
#                specified in the config/config.mk file (from the project root)
#                if it exists.
#                Alternatively, users may pass the name of a custom configuration
#                file to the Master Makefile by specifying an argument to make.
#                i.e. make CONFIG=<custom.mk>
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# [Required] build values
VARIANT        ?=
PLATFORM       ?=
DEVICE_NAME    ?=
NODE_NAME      ?=
FRIENDLY_NAME  ?=

# [Optional] static network values
STATIC_IP      ?=
STATIC_GATEWAY ?=
STATIC_SUBNET  ?=
STATIC_DNS1    ?=
STATIC_DNS2    ?=

# [Optional] communications poth to target
COMM_PATH     ?=
