# ------------------------------------------------------------------------------
#  File:         esp32.yaml
#  File Type:    ESPHome YAML Include
#  Purpose:      ESP32 board and framework configuration
#  Version:      0.8.0d
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  Modular include for ESPHome projects targeting ESP32-S3.
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
#  YAML linter configuration
#   - Disables quoted-strings rule for improved readability
# ------------------------------------------------------------------------------
# yamllint disable rule:quoted-strings


# ------------------------------------------------------------------------------
#  ESP32 (30 Pin Package) Dev Module standard Pinout Map (Vertical, Top View)
# ------------------------------------------------------------------------------
#
#                                     ┌────────────────┐
#                                 EN ─┤ 01 ┌──────┐ 30 ├─ GPIO23  SPI_MOSI  VSPI_MOSI
#               VP  ADC1_CH0  GPIO36 ─┤ 02 │      │ 29 ├─ GPIO22  I2C_SCL
#               VN  ADC1_CH3  GPIO39 ─┤ 03 │      │ 28 ├─ GPIO01  U0TXD     CLK3
#                   ADC1_CH6  GPIO34 ─┤ 04 └──────┘ 27 ├─ GPIO03  U0RXD     CLK2
#                   ADC1_CH7  GPIO35 ─┤ 05          26 ├─ GPIO21  I2C_SDA
#   XTAL32  TOUCH9  ADC1_CH4  GPIO32 ─┤ 06          25 ├─ GPIO19  SPI_MISO  VSPI_MISO
#           TOUCH8  ADC1_CH5  GPIO33 ─┤ 07          24 ├─ GPIO18  SPI_SCK   VSPI_CLK
#             DAC1  ADC2_CH8  GPIO25 ─┤ 08  ESP-32  23 ├─ GPIO05  VSPI_CS
#             DAC2  ADC2_CH9  GPIO26 ─┤ 09          22 ├─ GPIO17  U2TXD
#           TOUCH7  ADC2_CH7  GPIO27 ─┤ 10          21 ├─ GPIO16  U2RXD
# HSPI_CLK  TOUCH6  ADC2_CH6  GPIO14 ─┤ 11          20 ├─ GPIO04  ADC2_CH0  TOUCH0
# HSPI_MISO TOUCH5  ADC2_CH5  GPIO12 ─┤ 12          19 ├─ GPIO02  ADC2_CH2  TOUCH2   SPI_CS
# HSPI_MOSI TOUCH4  ADC2_CH4  GPIO13 ─┤ 13          18 ├─ GPIO15  ADC2_CH3  TOUCH3   HSPI_CS
#                                GND ─┤ 14          17 ├─ GND
#                         5V     VIN ─┤ 15          16 ├─ VCC     3.3V
#                                     └──────USB───────┘
#
#  Notes:
#    - GPIO6-11 are used for SPI flash and are not available for user IO
#    - GPIO1 (TX0), GPIO3 (RX0) are UART0 (serial console) pins
#      - can be repurposed if not using serial, but be careful
#        if you need serial logging or programming
#    - GPIO2 is a strapping pin; must be low at boot for some modules
#      - this pin should not be pulled high or low at boot/reset
#      - avoid using for output that could interfere with boot
#    - GPIO5  is a strapping pin; must be high at boot
#      - this pin should not be pulled low at boot/reset
#      - avoid using for output or with pull-ups
#    - GPIO3 is Rx pin for flashing/debugging
#    - GPIO12 is a strapping pin; high at boot selects high voltage for flash
#      - this pin should not be pulled high or low at boot/reset
#      - avoid using for output or with pull-ups
#    - GPIO15 is a strapping pin; must be low at boot
#      - this pin should not be pulled high or low at boot/reset
#      - avoid using for output or with pull-ups
#    - GPIO16, GPIO17 is used for PSRAM on some modules
#        - check your board’s datasheet before using
#    - GPIO20, GPIO24 is not available on most ESP32 modules
#    - GPIO34-GPIO39 are input only
#    - not all pins are available on all modules; check your board's datasheet
#    - see ESP32 datasheet for full alternate functions
#
#  ESP32 Datasheet: 
#      https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf
#
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
#  Target ESP32 board and Arduino framework declaration
#   - board: Target ESP32 Dev Module (ESP-WROOM-32)
#   - framework: Arduino core for ESP32
#   - Parameters:
#       board: Target board (e.g., esp32dev)
#       framework.type: Framework type (e.g., arduino)
# ------------------------------------------------------------------------------
esp32:
  board: esp32dev                 # board Target board: ESP32 Dev Module (ESP-WROOM-32)
  framework:
    type: arduino                 # framework.type Arduino core for ESP32

# ------------------------------------------------------------------------------
#  SPI bus configuration for ST7789V display module
#   - Configures SPI bus for display communication
#   - Assigns clock and MOSI pins
#   - Parameters:
#       clk_pin: Clock pin for SPI
#       mosi_pin: MOSI data pin
# ------------------------------------------------------------------------------
spi:
  clk_pin: GPIO18              # clk_pin Clock pin for SPI
  mosi_pin: GPIO23             # param mosi_pin MOSI data pin

# ------------------------------------------------------------------------------
#  Display Interface Configuration
#   - Configures GPIO pins for display communication
#   - Assigns Chip Select, Data/Command, and Reset pins
#   - Parameters:
#       display_cs: pin Chip Select pin
#       display_dc: pin Data/Command pin
#       display_reset: pin Reset pin
# ------------------------------------------------------------------------------
substitutions:
  display_cs_pin:    "GPIO13"       # cs_pin Chip select pin
  display_dc_pin:    "GPIO04"       # dc_pin Data/command pin
  display_reset_pin: "GPIO17"       # reset_pin Reset line
