# ------------------------------------------------------------------------------
#  @file        logging.yaml
#  @brief       Common esphome logging subsystem configuration.
#
#  @author      Roland Tembo Hendel
#  @email       rhendel@nexuslogic.com
#
#  @license     GNU General Public License v3.0
#               SPDX-License-Identifier: GPL-3.0-or-later
#  @copyright   Copyright (c) 2025 Roland Tembo Hendel
#               This program is free software: you can redistribute it and/or
#               modify it under the terms of the GNU General Public License
#               as published by the Free Software Foundation, either version 3
#               of the License, or (at your option) any later version.
#
#               This program is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public License
#               along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#  @note        Co-developed with ChatGPT by OpenAI.
# ------------------------------------------------------------------------------

# @brief ESPHome logging subsystem
# @details Enables serial and OTA log output, controls verbosity
logger:
  level: DEBUG           # @param level Global log level (NONE, ERROR, WARN, INFO, DEBUG, VERBOSE)
  logs:
    main: DEBUG          # @param main Module-specific log level for 'main'

  # @brief Action on log message reception
  on_message:
    - lambda: |-
        ESP_LOGI("main", "Firmware version: ${version}");
