# ==============================================================================
#  File:         phb-test.yaml
#  File Type:    YAML Main
#  Purpose:      PumpHouseBoss Test Harness Variant Main
#  Version:      0.10.0d
#  Date:         2025-08-22
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  Hardware test fixture for PumpHouseBoss Line of Water
#                Distribution System Monitor and Controllers.
#
#  Features:     - 8 programmable PWM output lines to simulate Hall-effect
#                  flow sensors
#                - 8 input lines to simulate external solenoid control
#                - 4 line LCD (lcd_pcf8574 interface)
#                - Menu-driven line toggle enable/disable
#                - Modular configuration via YAML fragments
#                - System state, diagnostics, and network info
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ==============================================================================

# yamllint disable rule:quoted-strings


# ------------------------------------------------------------------------------
#  Node identity, version, and hardware pin assignments
#
substitutions:
  defNodeName:         "__NODE_NAME__"
  defFriendlyName:     "__FRIENDLY_NAME__"
  defVersion:          "__VERSION__"
  defControlPoints:    "__CONTROL_POINTS__"
  defManualModeTimer:  60
  defAutoScrollTimer:  3
  pinSDA:              "GPIO18"
  pinSCL:              "GPIO09"
  pinBTNBlue:          "GPIO04"
  pinBTNGreen:         "GPIO05"
  pinBTNYellow:        "GPIO06"
  pinLEDWhite:         "GPIO07"
  pinLEDGreen:         "GPIO15"
  pinLEDBlue:          "GPIO16"
  pinLEDRed:           "GPIO17"
  pinTP0Out:           "GPIO43"
  pinTP0In:            "GPIO44"
  pinTP1Out:           "GPIO01"
  pinTP1In:            "GPIO02"
  pinTP2Out:           "GPIO42"
  pinTP2In:            "GPIO41"
  pinTP3Out:           "GPIO40"
  pinTP3In:            "GPIO39"
  pinTP4Out:           "GPIO48"
  pinTP4In:            "GPIO47"
  pinTP5Out:           "GPIO21"
  pinTP5In:            "GPIO20"
  pinTP6Out:           "GPIO13"
  pinTP6In:            "GPIO12"
  pinTP7Out:           "GPIO11"
  pinTP7In:            "GPIO10"


# ------------------------------------------------------------------------------
#  External Components
#  Note; something is broken in the esphome component registration process
#        Until this is fixed, we need to include the components manually.
#        See esphome:includes (below)
#
external_components:
  - source:
      type: local
      path: ../../components/esp32bootcode
  - source:
      type: local
      path: components/phb-test


# ------------------------------------------------------------------------------
#  Common and local package includes for modular configuration
#
packages:
  # common (shared) YAML packages
  esp32s3:     !include ../../packages/esp32s3.yaml
  wifi:        !include ../../packages/wifi.yaml
  ota:         !include ../../packages/ota.yaml
  web:         !include ../../packages/web_server.yaml
  logging:     !include ../../packages/logging.yaml
  # local YAML packages
  control:     !include packages/controls.yaml
  display:     !include packages/display.yaml


# ------------------------------------------------------------------------------
#  Hardware & Logic Fragments
#
output:        !include fragments/outputs.yaml
sensor:        !include fragments/sensors.yaml
binary_sensor: !include fragments/binary_sensors.yaml
number:        !include fragments/numbers.yaml
text_sensor:   !include fragments/text_sensors.yaml
switch:        !include fragments/switches.yaml


# ------------------------------------------------------------------------------
#  ESPHome metadata and boot logic
#  Note: something is broken in the esphome component registration process
#        Until this is fixed, we need to include the components manually.
#        See esphome:includes (below)
#
esphome:
  name: __DEVICE_NAME__
  friendly_name: __FRIENDLY_NAME__
  includes:
    - ../../components/esp32bootcode/esp32bootcode.h
    -  components/phb-test/phb-test.h
  on_boot:
    priority: 600
    then:
      - text_sensor.template.publish:
          id: textFriendlyName
          state: "__FRIENDLY_NAME__"
      - text_sensor.template.publish:
          id: textVersion
          state: "__VERSION__"
      - text_sensor.template.publish:
          id: textNodeName
          state: "__NODE_NAME__"
      - text_sensor.template.publish:
          id: textIPAddress
          state: "No Connection"
      - text_sensor.template.publish:
          id: textOperatingMode
          state: "NORMAL"
      - lambda: |-
          auto &bootReason = esphome::bootcode::BootCode::get();
          id(textResetReason).publish_state(bootReason.mGetBootReason().c_str());


# ------------------------------------------------------------------------------
#  I2C Bus Configuration
#
i2c:
  sda: ${pinSDA}
  scl: ${pinSCL}
  scan: true
