# ==============================================================================
#  File:         phb-test.mk
#  File Type:    Makefile
#  Purpose:      PumpHouseBoss Test Harness Variant build variables and defaults
#  Version:      0.10.0d
#  Date:         2025-07-26
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This variant-specific configuration file describes default
#                values used to build the PumpHouseBoss Test Harness
#                implementation.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ==============================================================================

# Required configuration values
VARIANT        ?= phb-test
PLATFORM       ?= esp32s3
DEVICE_NAME    ?= phb-test
CONTROL_POINTS ?= 8
NODE_NAME      ?= phb-test-node
FRIENDLY_NAME  ?= PumpHouseBoss Test
