# ------------------------------------------------------------------------------
#  File:         variant.mk
#  File Type:    Makefile Variant Configuration
#  Purpose:      PumpHouseBoss Standard Variant build variables and defaults
#  Version:      0.7.1
#  Date:         2025-07-26
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This variant-specific configuration file describes default values
#                used to build the PumpHouseBoss Standard implementation.
#                Includes:
#                - Espressif ESP-32-S Development Board Type C (30 pin)
#                - Support for up to 6 ports (default is 1)
#                - 3 LED status outputs
#                - External reset button
#                - External emergency shut-off button
#                - USB programming/debugging port
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# Required configuration values
VARIANT        ?= phb-std
PLATFORM       ?= esp32
DEVICE_NAME    ?= phb-std
NODE_NAME      ?= phb-std-00
FRIENDLY_NAME  ?= PumpHouse Boss - Standard

# [Optional] static network values
NUM_PORTS      ?= 1

# [Optional] programming values
OTA_NAME       ?= phb-std-00.local
