# ------------------------------------------------------------------------------
#  File:         mkdocs.yml
#  File Type:    MkDocs Configuration
#  Purpose:      Documentation site configuration for PumpHouse Boss
#  Version:      0.7.1
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  Configuration for MkDocs static documentation site, navigation,
#                theme, and build output directory.
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ------------------------------------------------------------------------------

site_name: PumpHouseBoss Documentation
nav:
  - Home: README.md
  - DESCRIPTION:
     - PumpHouseBoss Standard:
        - Overview: phb-std-overview.md
        - Hardware: phb-std-hardware.md
     - PumpHouseBoss Professional:
        - Overview: phb-pro-overview.md
        - Hardware: phb-pro-hardware.md
  - RELEASE NOTES: RELEASE.md
  - CHANGELOG: CHANGELOG.md
  - STANDARDS: STANDARDS.md
  - RELEASE-CHECKLIST: RELEASE-CHECKLIST.md
  - GIT-COPILOT: GIT-COPILOT.md
  - TODO: TODO.md
  - SOURCE CODE:
     - Variants:
        - PHB Std: phb-std.md
        - PHB Pro: phb-pro.md
     - Common:
        - Display: display_st7789.md
        - esp32: esp32.md
        - esp32s3: esp32s3.md
        - Logging: logging.md
        - OTA: ota.md
        - Watchdog: watchdog.md
        - Web Server: web_server.md
        - WiFi: wifi.md
        - Secrets Template: secrets.template.md
repo_url: https://github.com/hucklesberries/PumpHouseBoss
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
docs_dir: md
site_dir: html
