# ------------------------------------------------------------------------------
#  File:         mkdocs.yml
#  File Type:    MkDocs Configuration
#  Purpose:      Documentation site configuration for PumpHouse Boss
#  Version:      0.8.0d
#  Date:         2025-07-24
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  Configuration for MkDocs static documentation site, navigation,
#                theme, and build output directory.
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
# ------------------------------------------------------------------------------

site_name: PumpHouseBoss Documentation
repo_url: https://github.com/hucklesberries/PumpHouseBoss
site_url: https://hucklesberries.github.io/PumpHouseBoss/
nav:
  - HOME: 
      - Start Here: Home.md
      - Overview: Overview.md
      - Getting Started: Getting-Started.md
      - Hardware Overview: Hardware-Overview.md
      - Firmware & Configuration: Firmware-and-Configuration.md
      - Usage & Troubleshooting: Usage-and-Troubleshooting.md
      - Developer Guide: Developer-Guide.md
      - FAQ: FAQ.md
      - Contact & Support: Contact-and-Support.md
  - PRODUCT VARIANTS:
     - PumpHouseBoss Standard:
        - Overview: phb-std-overview.md
        - Hardware: phb-std-hardware.md
     - PumpHouseBoss Professional:
        - Overview: phb-pro-overview.md
        - Hardware: phb-pro-hardware.md
  - PROJECT DOCUMENTATION:
     - READ ME: README.md
     - CONTRIBUTING: CONTRIBUTING.md
     - STANDARDS: STANDARDS.md
     - RELEASE-CHECKLIST: RELEASE-CHECKLIST.md
     - RELEASE NOTES: RELEASE.md
     - CHANGELOG: CHANGELOG.md
     - TODO: TODO.md
  - SOURCE CODE:
     - Variants:
        - PHB Std: phb-std.md
        - PHB Pro: phb-pro.md
     - Common:
        - Display: display_st7789.md
        - Display PCF8574: display_pcf8574.md
        - Indications: indications.md
        - MMU: mmu.md
        - API: api.md
        - esp32: esp32.md
        - esp32s3: esp32s3.md
        - Logging: logging.md
        - OTA: ota.md
        - Watchdog: watchdog.md
        - Web Server: web_server.md
        - WiFi: wifi.md
        - Secrets Template: secrets.template.md
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
docs_dir: mkdocs-staged
site_dir: site-staged
