# ------------------------------------------------------------------------------
#  File:         variant.mk
#  File Type:    Makefile Variant Configuration
#  Purpose:      PumpHouseBoss Pro Max Variant build variables and defaults
#  Version:      0.7.0
#  Date:         2025-07-26
#  Author:       Roland Tembo Hendel <rhendel@nexuslogic.com>
#
#  Description:  This variant-specific configuration file describes default values
#                used to build the PumpHouseBoss Pro Max implementation.
#                Includes:
#                - Espressif ESP-32-S3 Development Board Type C (44 pin)
#                - Support for up to 8 ports
#                - Waveshare Pico LCD 1.3" 240x240 Display Module
#                - Integrated menu and controls
#                - USB programming/debugging port
#
#  License:      GNU General Public License v3.0
#                SPDX-License-Identifier: GPL-3.0-or-later
#  Copyright:    (c) 2025 Roland Tembo Hendel
#                This program is free software: you can redistribute it and/or
#                modify it under the terms of the GNU General Public License.
#
#  Note:         DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
# ------------------------------------------------------------------------------


# Required configuration values
VARIANT        ?= phb-pro-max
PLATFORM       ?= esp32s3
DEVICE_NAME    ?= phb-pro-max
NODE_NAME      ?= phb-pro-max-00
FRIENDLY_NAME  ?= PumpHouse Boss - Pro Max

# [Optional] static network values
NUM_PORTS      ?= 8

# [Optional] programming values
OTA_NAME       ?= phb-pro-max-00.local
